insert into t_package (package_name, app_name, merchant_number, status)
VALUES ('com.sdwq.clickvay', 'SDong----刘', '2001', 'CREATED'),
       ('com.casilnss.sddvuiaiss', 'DiVa----刘', '2001', 'CREATED'),
       ('com.n2m4j1.k2i9o1', '古泰－yong dong(已发未上)', '2002', 'CREATED'),
       ('com.skkjjs.bsjkopw', 'ezDong主林 v2 ----耿', '2003', 'CREATED'),
       ('com.kjskj.xyiuqwe', 'ezDong主林 v3 ----耿', '2003', 'CREATED'),
       ('com.biezaixx', 'Tiger cash(已发未上)', '2004', 'CREATED'),
       ('com.xinponet.android.flashvay', 'Flash vay 新普互联(备案成功)----刘', '2005', 'CREATED'),
       ('com.odokoss.vynsidow.vvsdkiww', '马甲包 Vi online----刘', '2005', 'CREATED'),
       ('com.ddiinn.kakasw.vaasvuive', '马甲包 vay vui vẻ----刘', '2005', 'CREATED'),
       ('com.getsils.younsdg', 'You Dong / J Dong盘石----刘', '2006', 'CREATED'),
       ('com.vici.vaytien', 'Có tiền xài 从杰----刘', '2007', 'CREATED'),
       ('com.vaynhann', 'Vay nhanh厦门贸易(不维护)', '2008', 'CREATED'),
       ('com.biezaixia.gankuaishang', 'Easy Vay印飞----刘', '2009', 'CREATED'),
       ('com.iwjisag.fdosnsw', 'Fdong小牛科技----刘', '2010', 'CREATED'),
       ('com.fvvayy.biexiale', '马甲包Fvay----刘', '2010', 'CREATED'),
       ('com.casilnis.fnncoia', '马甲包Fnong----刘', '2010', 'CREATED'),
       ('com.wusidheis.fcatniab', '马甲包Fcat----刘', '2010', 'CREATED'),
       ('com.dudussiw.tuiduangt', '马甲包Túi đựng tiền----刘', '2010', 'CREATED'),
       ('com.swishwu.ffcashf', '马甲包Fcash----刘', '2010', 'CREATED'),
       ('com.iovcxuj.mkxco', 'Thỏ Vay----刘', '2011', 'CREATED'),
       ('com.vaydep.wing', 'xvay微云(典当备案) ----耿', '2012', 'CREATED'),
       ('com.bbyabe.svsuvll', 'BeVay(已发未上-找谷歌账号)', '2013', 'CREATED'),
       ('com.jiunbom.mobna', 'Ví bây giờ(典当备案) ----耿', '2014', 'CREATED'),
       ('com.gewqs.asd', 'nhiều tiền主包 ----耿', '2015', 'CREATED'),
       ('com.yasdhkq.shd', 'nhiều tiền主包 ----耿', '2015', 'CREATED'),
       ('com.sdjkw.iiuooia', 'vietdong ----耿', '2017', 'CREATED'),
       ('com.sjkxqw.uehxlqz', 'trieudong ----耿', '2017', 'CREATED'),
       ('com.usia.qqcah', 'Qcash2015 nhiều tiền主包 ----耿', '2018', 'CREATED'),
       ('com.tdong.tco', 'Tdong----刘', '2019', 'CREATED'),
       ('com.kjsd.qwwkksbe ', 'Sg Vay ----耿', '2020', 'CREATED'),
       ('com.yuioqwe.cash', 'Wdong/Wcash ----耿', '2021', 'CREATED'),
       ('com.vnan.vvn', 'Mog(开发者名称敏感 手动下架0810) ----耿', '2022', 'CREATED'),
       ('com.qrewfo.roygfuq', '马甲包2000 ----耿', '2022', 'CREATED'),
       ('com.kktis.lddngg', 'ivay----刘', '2023', 'CREATED'),
       ('com.leningd.llddoo', 'Ldong----刘', '2023', 'CREATED'),
       ('com.bydhh.bunengxia', '联运包----刘', '2023', 'CREATED'),
       ('com.nisish.vanongss', 'vay nong----刘', '2023', 'CREATED'),
       ('com.ccsshh.cassddonn', 'Cashdong----刘', '2023', 'CREATED'),
       ('com.bsussu.youyaay', 'Youvay----刘', '2023', 'CREATED'),
       ('com.asdlk.qwoiexzh', 'Viet Money  ----耿', '2024', 'CREATED'),
       ('com.slkjqlkl.qwezqa', 'Vay nhanh(马甲包1)  ----耿', '2024', 'CREATED'),
       ('com.sajkdh.uavipfsad', 'Vgold (马甲包2, 客户自上)  ----耿', '2024', 'CREATED'),
       ('com.phucvi.vnm', 'Phúc Ví(未运营) ----耿', '2025', 'CREATED'),
       ('com.wewinwe.finishibyebe', 'Lucky pay----刘', '2026', 'CREATED'),
       ('com.wskeiuswj.woriia', 'King Pay(马甲包)----刘', '2026', 'CREATED'),
       ('com.stvicash.stvinhanh', 'S nhanh(典当备案) ----耿', '2027', 'CREATED'),
       ('com.qwxawq.jax', 'Cho bạn tiền', '2028', 'CREATED'),
       ('com.chons.bance', 'sky pay(马甲包已备案)', '2028', 'CREATED'),
       ('com.duaban.vay', 'Vay như chớp 2000的马甲包', '2030', 'CREATED'),
       ('com.vay.tienle', 'Vay Lẹ 7000的马甲包', '2030', 'CREATED'),
       ('com.kunshan.bumblebee', 'BumblebeeVay', '2031', 'CREATED'),
       ('com.sbd.vvmsn', 'Sky Dong', '2031', 'CREATED'),
       ('com.icash.dong', 'MoDong)', '2033', 'CREATED'),
       ('com.honni.hanh', 'Vay Khong', '2034', 'CREATED'),
       ('com.rwgsodhe.three', 'TaiChinhOnline', '2035', 'CREATED'),
       ('net.bluecredittech.mars', 'Bluecredit', '2036', 'CREATED'),
       ('net.bdong.dohm', '马甲 B dong', '2036', 'CREATED'),
       ('com.jjy.ohdfwdxb', 'Đi đâu vay(暂时不上架20190619)', '2037', 'CREATED'),
       ('com.vay.mob', 'Vay mob', '2039', 'CREATED'),
       ('com.cloud.cash', 'Cash i', '2041', 'CREATED'),
       ('com.itenn.vemf', 'iTien(暂时不上架20190619)', '2042', 'CREATED'),
       ('com.djjwk.sjwjkxs', ' ----耿', '2043', 'CREATED'),
       ('com.ldjjy.hbtsbl', 'FlyCash(20190704未回复)', '2045', 'CREATED'),
       ('com.ucdong', 'ucDong', '2046', 'CREATED'),
       ('com.bautroi.tory', 'BauTroi(一直没回复)', '2047', 'CREATED'),
       ('com.yesn.yesvay', 'Okvay', '2048', 'CREATED'),
       ('com.sadsadtt.ivala', 'BayVay（营业执照） -hc', '2049', 'CREATED'),
       ('com.ksadguiwq.hivay', ' Lập Tức Vay -hc', '2050', 'CREATED'),
       ('com.hidi.lhasdjh', '马甲包 -hc', '2050', 'CREATED'),
       ('com.vinvay.goglee', ' Vin Vay -hc', '2051', 'CREATED'),
       ('com.sdjkhaksd.isujss', 'FirstCash(营业执照因有两个手动下了) -hc', '2052', 'CREATED'),
       ('com.ccas.ttvay', '33vay(营业执照) -hc', '2052', 'CREATED'),
       ('com.sdong.mvnb', 'SunDong -hc', '2053', 'CREATED'),
       ('com.kisla.ayoola', 'AYOOLA -hc', '2053', 'CREATED'),
       ('com.sunnyLoan.opqrstvn', 'Chovay -hc', '2054', 'CREATED'),
       ('com.sadoiqhw.vietdong', '马甲包（有牌照） -hc', '2054', 'CREATED'),
       ('com.vaytocdo.vie1', 'Vay Tocdo -hc', '2055', 'CREATED'),
       ('com.askldgtt.kasg', 'Vay Tocdo马甲包 -hc', '2055', 'CREATED'),
       ('com.ksadjoiqw.vvdt', 'Gold Pocket -hc', '2056', 'CREATED'),
       ('com.lashdhasd.pago', 'Ticha -hc', '2057', 'CREATED'),
       ('com.okdong.vn', 'Okdong -hc', '2058', 'CREATED'),
       ('com.skkqjx.hhkqkkx', 'V2 com.oplia.ujshnzqks', '2059', 'CREATED'),
       ('com.wqijd.uwysaqxzsde', 'Ví tín dụng(不维护)', '2060', 'CREATED'),
       ('com.vindong.app', 'Vindong -hc', '2061', 'CREATED'),
       ('com.kasjdh.vct', 'Tín dụng siêu tốc online -hc', '2062', 'CREATED'),
       ('com.lkdasuq.mnbklxcoo', 'Lendong', '2063', 'CREATED'),
       ('com.sadhllas.vaynhe', 'Vay Nhe(换了UI的包 执照备案成功)', '2063', 'CREATED'),
       ('com.heycok.amidnes', 'Hey wallet(有牌照)', '2064', 'CREATED'),
       ('com.comdong.ayimeme', 'Eloan库', '2065', 'CREATED'),
       ('com.mklopx.tyux', 'Flying loan', '2066', 'CREATED'),
       ('com.asdsadcc.mvay', 'aDong（v11）（营业执照） -hc', '2067', 'CREATED'),
       ('com.skongs.ldonglon', 'Vân tinh thải', '2068', 'CREATED'),
       ('com.seekvay.suncase', 'Suncash', '2069', 'CREATED'),
       ('domnan.suncase.nan', 'VCVAy(上不去送的马甲包)', '2069', 'CREATED'),
       ('umliop.lkhj.daslp', 'vay đơn giản(20190704 已发包)', '2070', 'CREATED'),
       ('com.trong.giayyu', 'Second loan', '2071', 'CREATED'),
       ('ksdlop.lomsak.uidso', 'vay tiền nóng', '2072', 'CREATED'),
       ('com.vayvang.com', 'Vay vàng', '2074', 'CREATED'),
       ('com.tuigaotin.xinyongmidai', 'Túi gạo tín dụng', '2075', 'CREATED'),
       ('com.yccash.vn', 'YC Cash(整理资料未开始上线)', '2076', 'CREATED'),
       ('com.tini.me', 'Vaynha', '2077', 'CREATED'),
       ('com.oncash.mjzdxx', 'On cash(提供源码 客户自己打包上架) com.skkqjx.hhkqkkx', '2079', 'CREATED'),
       ('com.pdaidai.toocharea', '668Vay----刘', '2080', 'CREATED'),
       ('com.kosius.ezsjdys', 'EZVay----刘', '2081', 'CREATED'),
       ('com.wonderw.finishbye', 'EZVay----刘', '2081', 'CREATED'),
       ('com.esec.katana', 'Esec(已提供包，等待对方上架) -hc', '2082', 'CREATED'),
       ('com.saigoncash.sikuo', 'SaigonCash', '2083', 'CREATED'),
       ('com.mxutu.icash', 'Vietpay', '2084', 'CREATED'),
       ('com.vcashs.emvici', 'Vcash', '2084', 'CREATED'),
       ('com.ms.easydong', 'Easydong(20190705交付)', '2085', 'CREATED'),
       ('com.uikidds.dduikksas', 'Vay chó nhanh----刘-', '2086', 'CREATED'),
       ('com.kajssh.vivay2', 'Vaycoi -hc', '2087', 'CREATED'),
       ('com.kasgdh.alivay', 'Cấp trên Vay(20190805交付，等待对方上架v11) -hc', '2088', 'CREATED'),
       ('com.vnmony.dong', 'VNmony (20190718))', '2089', 'CREATED'),
       ('com.vi.credit', 'Vi Credit(已提供包，等待对方上架)', '2090', 'CREATED'),
       ('com.xegood.cash', 'GoodCash ', '2092', 'CREATED'),
       ('com.msier.xinexi', 'Yoho Cash ---赵', '2092', 'CREATED'),
       ('com.D2094.h5', 'vay100(20190725交付)', '2094', 'CREATED'),
       ('jdsin.uqowe.vayoes', 'vay186', '2094', 'CREATED'),
       ('com.tengdac.tengdafinc', 'Sunvay', '2097', 'CREATED'),
       ('com.eqwall.casex', 'Cash Online', '2098', 'CREATED'),
       ('com.victkin.bnengxias', 'vict vay----刘', '2099', 'CREATED'),
       ('com.good.vay', 'GoodVay----hc', '2100', 'CREATED'),
       ('com.ta.vay', 'TaVay----耿', '2102', 'CREATED'),
       ('com.vaytienonline.finance', 'Vaytien Online --赵', '2103', 'CREATED'),
       ('com.vipdong.vaydong', 'VIP Dong ---赵', '2108', 'CREATED'),
       ('vn.banvay.lite', 'Bạn vay tôi', '9000', 'CREATED'),
       ('com.hongcheng.vaydong', 'VayDong VN', '9001', 'CREATED'),
       ('com.vvtien.vn', 'funmoney', '9002', 'CREATED'),
       ('com.momoloan.vvn', 'Vay nào', '9002', 'CREATED'),
       ('com.weiyun.on.dong', 'On Dong（2079家的，图标一样，我们的源码）', '9002', 'CREATED'),
       ('com.didivay.vn', 'Didi Vay', '9002', 'CREATED'),
       ('com.vaydep.happycash', 'happycash', '9002', 'CREATED'),
       ('com.madong.vn', 'mydong', '9002', 'CREATED'),
       ('com.financ.vivu', 'ViVu', '9002', 'CREATED'),
       ('com.weiyun.vi.dong', 'Vi Dong（2079家的，图标一样，我们的源码）', '9002', 'CREATED'),
       ('com.vitian.wocash', 'Hi Dong', '9002', 'CREATED'),
       ('com.yvaysash.vvn', 'Y-vay', '9002', 'CREATED'),
       ('com.szwy.vidientu', 'Vi dien tu', '9002', 'CREATED');